version: '3.5'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.8
    restart: always
    hostname: mongo
    environment:
      TZ: UTC # UTC, Europe/Amsterdam, America/Lima
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./files/mongo:/docker-entrypoint-initdb.d
      - ./files/mongo/mongo-init.js
    command: mongod --bind_ip_all
    networks:
      - local

networks:
  local:
    name: local_network